### ISSUE TITLE
Document how to add a third-party database (data and technology) into UK RSP

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#103]
- Need to be able to expose datasets, hosted in Qserv, via RSP TAP
- Understand how to generate custom schema for use with TAP service

**Comment by markgbeckett** [comment]
Have worked out how to add user-provided catalogue to portal view of TAP service. Need to create a YAML file to describe catalogue, but would be wise to automate for more complex catalogues.

Needs to be documented.

**Comment by markgbeckett** [comment]
WP3.5 data will be used to test understanding of how to generate custom schema.

**Comment by stvoutsin** [comment]
Documentation has been added here: https://github.com/lsst-uk/rsp-uk/blob/e09fae881d2f1782eace2e0da5b416f44acb07a8/notes/20220609-Adding-custom-dbs-RSP.txt

**Comment by markgbeckett** [comment]
Documented in D2.2.3.
