### ISSUE TITLE
Create local source for DP0.1

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#104]
Reduce risk of having to ask for support from IN2P3 when ingesting

**Comment by markgbeckett** [comment]
@manzi1 has created a local copy of the partitioned CSV files for DP0.1 source on Somerville. Will add a note to Admin docs, so is easy to find.

**Comment by markgbeckett** [comment]
@MikeeRead documented location of DP0.1 source.

**Comment by GregBlow** [comment]
documented here: 
https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2964455429/New+Qserv+install+on+Somerville+MkII
