### ISSUE TITLE
Agree list of ancillary datasets to be included in UKDAC1

### ISSUE THREAD

**Issue by bobmann** [lsst-uk/ukdac1#11]

**Comment by markgbeckett** [comment]
Ancillary list reviewed and approved by Stephen Smartt. See:

https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/766869516/Identification+of+ancillary+surveys

**Comment by tms-epcc** [comment]
Hi George, I am looking into how to make zenhub useful in advance of the demo I will give on Friday 19th to you an Bob.  I see this issue is marked as Done but it has not been closed.  Is there a reason for that? Cheers, Terry
