### ISSUE TITLE
Configure Firefly to access PS1 catalogue through TAP service

### ISSUE THREAD

**Issue by bobmann** [lsst-uk/ukdac1#16]

**Comment by markgbeckett** [comment]
Stelios waiting on credential to access Qserv (Craig to provide).

**Comment by markgbeckett** [comment]
- Stelios has configured TAP service, in RSP, to access Qserv (DP0.1). 
- Due to limitation in TAP service, only synchronous queries are supported (need Google Cloud Storage for asynchronous queries).

**Comment by markgbeckett** [comment]
PS1 will not be migrated to Qserv in short term. It is accessible via VDFS TAP service, the URL of which needs to be manually entered into the TAP Service field in Firefly.
