### ISSUE TITLE
Implement TAP Service for PS1 database

### ISSUE THREAD

**Issue by bobmann** [lsst-uk/ukdac1#19]

**Comment by markgbeckett** [comment]
Mike is creating schema, ready for insertion into TAP service. Once complete, will pass to Stelios for setting up.

**Comment by markgbeckett** [comment]
Mike has created schema and passed to Stelios for insertion into TAP service.

**Comment by markgbeckett** [comment]
In the first instance, we will publish PS1 via VDFS rather than as a separate TAP service.
Known stability issues with VDFS TAP service to be investigated by Stelios.
