### ISSUE TITLE
Operate UKDAC1 Helpdesk

### ISSUE THREAD

**Issue by bobmann** [lsst-uk/ukdac1#22]
This will/does provide support for the the following:
- UK outputs
- Lasair
- IRIS for UK users

All other support aspects are provided via the Rubin community forum. 
Relevant LSST:UK staff are members of this forum.

**Comment by markgbeckett** [comment]
Lasair and IRIS infrastructure (Somerville) supported during period, via email and GitHub - https://github.com/lsst-uk/somerville-operations and https://github.com/lsst-uk/lasair/issues.
