### ISSUE TITLE
Update Qserv Evaluation Report, based on new evidence

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#52]
Original report is LUSC-A-07 (see George Beckett for MS Word version).
LUSC  published version is https://lsst-uk.atlassian.net/wiki/download/attachments/1146928/LUSC-A-07_qserv_evaluation.pdf?api=v2

**Comment by tms-epcc** [comment]
@manzi1 - see  LUSC  published version of Teng's report at https://lsst-uk.atlassian.net/wiki/download/attachments/1146928/LUSC-A-07_qserv_evaluation.pdf?api=v2

**Comment by markgbeckett** [comment]
- Craig has local copy, at time of meeting, to be uploaded to wiki.

**Comment by markgbeckett** [comment]
The value of doing this is too far diminished, so will not proceed. Replaced with evaluation of Somerville Qserv vs. IDF Qserv vs. IN2P3 Qserv.
