### ISSUE TITLE
 Ingesting a non-LSST dataset 

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ukdac1#80]
- Ingesting a non-LSST dataset (to gain experience of ingest process). WP3.11 has a modest-sized cross-match catalogue we could use (probably does not need chunking), plus we may soon have a big catalogue from WP3.5 (probably will need chunking).

**Comment by markgbeckett** [comment]
Candidate for this is VISTA data

**Comment by markgbeckett** [comment]
Mike has successfully ingested data from WP3.11.
