### ISSUE TITLE
Connect UK RSP (on Somerville) to Local Vault Service

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#84]

**Comment by markgbeckett** [comment]
This has been proved in principal, but still to be implemented in production using the vault service at lsst.ac.uk (managed by Gareth Francis).
The main difference between our impl and US impl is token lifetime (US service issues tokens for 12 months; UK issues tokens for 30 days). Renewing the token every 30 days would be painful, so should be resolved before making the move in production.

**Comment by stvoutsin** [comment]
This has been done, so I'll close this one
