### ISSUE TITLE
Experiment with accessing FITS data with Butler using Nublado

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/ukdac1#89]
- [x] Mount some/any FITS files on an NFS share
- [x] Modify example notebooks to use data directory
- [ ] Run and report output for notebooks

**Comment by markgbeckett** [comment]
@stvoutsin will speak to @MikeeRead about identifying some suitable FITS images to experiment with.

**Comment by markgbeckett** [comment]
Mike was able to access VISTA data, via Butler instance, from Nublado client.

**Comment by markgbeckett** [comment]
@MikeeRead has asked @stvoutsin to make the two patches of VISTA data public. Stelios will do this once he has updated the RSP deployment (working on during w/b 21st Feb).

**Comment by markgbeckett** [comment]
ObsVISTA package likely to be required for some pipeline-related operations (e.g., ObsVISTA formatter, for individual exposures). Do not think ObsVISTA package is needed for coadds.
Expect it is straightforward to add ObsVISTA to setup script, though @stvoutsin spoke to SQuaRE team who adviced needs to be added to Docker image, and added to list of official notebook images.
@raphaelshirley will try adding ObsVISTA to his individual notebook instance, at startup.

**Comment by markgbeckett** [comment]
@stvoutsin has set up a shared Butler instance, based on test data from @MikeeRead and @raphaelshirley . This required read-write access to be enabled for the Butler. Next step is to check what happens when several users (e.g., @MikeeRead and @stvoutsin) try to run analysis using the Butler and, effectively, modify the Butler registry contents.

**Comment by markgbeckett** [comment]
@stvoutsin to check with @MikeeRead whether shared access to a Butler instance can lead to conflicting changes. For example, if a user runs a pipeline task that writes to the Butler. Aim to determine whether or not we have any concerns about how shared-access works.
