### ISSUE TITLE
Write D2.2.3 final report

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#90]

**Comment by markgbeckett** [comment]
21/JAN/22 -- @MikeeRead and @markgbeckett met to agree document structure. @markgbeckett then started a document in UoE Office365.

**Comment by markgbeckett** [comment]
Word skeleton shared with @MikeeRead and @manzi1.

**Comment by markgbeckett** [comment]
@MikeeRead shared mature draft with @markgbeckett for comment. Once reviewed, can be passed to @tms-epcc  for project review.

**Comment by markgbeckett** [comment]
Report submitted for review. Feedback from one reviewer has been received.

**Comment by markgbeckett** [comment]
Feedback received from reviewers and incorporated into revised version of deliverable, which has been passed to Exec Group for approval.

**Comment by tms-epcc** [comment]
14/SEP/22
- D2.2.3 approved at 26/AUG/22 Exec group and subsequently [published](https://lsst-uk.atlassian.net/wiki/download/attachments/1146928/lusc-b-25_ancillary-survey_ingestion.pdf?api=v2).
