### ISSUE TITLE
(Re-)ingest DP0.1 catalogues into UKDAC2 Qserv instance

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#99]
Qserv Version 10 deployment on new Somerville hardware

**Comment by markgbeckett** [comment]
@manzi1 will contact IN2P3 to arrange access to transfer files

**Comment by markgbeckett** [comment]
Initial delayed by access problems for server in France.

These are now resolved, but Craig now seeing issue with ingestion, which potentially related to Qserv bug.

Craig and Fabrice have meeting on Thr 28th to try to resolve.

**Comment by markgbeckett** [comment]
@manzi1 has reingested DP0.1 into new, 10-node Qserv instance. Failed at last step, so checking with Fabrice if this is an issue.

**Comment by markgbeckett** [comment]
No response from Craig, so will re-test when we re-ingest DP0.1 as part of @GregBlow's Qserv deployment testing.

**Comment by manzi1** [comment]
> No response from Craig, so will re-test when we re-ingest DP0.1 as part of @GregBlow's Qserv deployment testing.

@markgbeckett Hiya, I don't think I saw any emails/questions re Qserv. I might have missed them.

When I left, you had a fully working version of Qserv with DP01 fully ingested which successfully ran queries. 

If you have any questions or if I can help just drop me an email on craigmanzi@hotmail.co.uk 🙂
